Add playwright testing for the new web package
eclipse-thingweb/playground pull request #513
Opened 2023-10-13 13:07 UTC by SergioCasCeb

The implemented testing for the new web packages, tests only the visual aspects of the application rather than the functionality of each package. More tests will be added for the remaining console views such as OpenAPI, AsyncAPI, AAS AID, Defaults, and the visualization view.

2023-10-13 21:43 UTC, SergioCasCeb commented
All remaining tests have been added as well as the respective description in the README file. Fixes #513

2023-10-17 14:36 UTC, egekorkan requested changes

2023-10-17 14:36 UTC, egekorkan commented on packages/web-new/tests/test.spec.js
> +        await expect(AASView).toHaveClass("console-view aas-view hidden")
This one is failing with 
```
Expected string: "console-view aas-view hidden"
Received string: "console-view aas-view"
```

2023-10-17 14:41 UTC, egekorkan commented on packages/web-new/tests/test.spec.js
> +        await expect(AASView).toHaveClass("console-view aas-view hidden")
I think the expected string is wrong since you click on the tab thus make it not hidden anymore

2023-10-25 21:03 UTC, egekorkan commented
The tests are working except for one but they should not be run for all the browsers all the time and in developer machines. For example, my setup with Manjaro Linux is not supported by Playwright to install msedge. We should simply split a run with "all browsers" to another script that is run only in GitHub actions

Failing test: Open the tree visualization view with the thing template and modified the input values

2023-11-14 09:44 UTC, egekorkan commented
@SergioCasCeb there is another test failing now where the popup events are not found so all tests for settings pop up links (check Thingweb footer link etc.) are failing. I am not sure but is that side bar opening firing a popup event by default? It seems not the case but if I add `window.dispatchEvent(new CustomEvent("popup"));` at https://github.com/eclipse-thingweb/playground/blob/master/packages/web-new/src/scripts/settings-menu.js#L60, those failing tests pass. What do you think @SergioCasCeb ?

2023-11-14 10:02 UTC, egekorkan commented
@SergioCasCeb I have added that line of code but feel free to suggest another solution. I have also synced this branch with master.

2023-11-14 13:37 UTC, egekorkan commented
The failure seems to be a time issue and not about the event I have mentioned above. The PR is ready to merge. The tests failing in GitHub actions is due to missing tests in web-new but these are coming with #515

2023-11-14 13:37 UTC, merged